"""Trace the sho0pi wordmark PNGs into SVGs, plus the hover-morph React component.

Two cuts of the same lettering: a plain zero and a slashed zero, traced to static
SVGs. The hover-morph component is built from the slashed cut alone - its resting
glyph is that same drawing's first o, copied into the zero's slot - so the morph
never has to reconcile two separate generations of the art.
"""
import os, subprocess, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from trace import Trace, svg, FILL, INK, PAPER

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BRAND = os.path.join(ROOT, "public/brand")
SOURCES = {"wordmark": "sho0pi-slashed-zero.png", "wordmark-plain": "sho0pi.png"}
ZERO = 1        # o 0 p i - the zero is the second glyph left to right
O = 0

traces = {}
for name, png in SOURCES.items():
    t = traces[name] = Trace(os.path.join(ROOT, "logo", png))
    # the smile is the same ink as the letters, so only the letters flip on dark
    for suffix, ink in (("", None), ("-on-dark", PAPER)):
        open(f"{BRAND}/{name}{suffix}.svg", "w").write(svg(t.w, t.h, t.body(ink=ink), "sho0pi"))
    subprocess.run(["rsvg-convert", "-w", "1600", f"{BRAND}/{name}.svg",
                    "-o", f"{BRAND}/png/{name}-1600.png"], check=True)
    print(f"{name:15s} {t.w}x{t.h}  baseline y={t.baseline():.0f}  "
          f"descender={(t.h - t.baseline())/t.h:.3f} of height")

# ---- the morph component: the wordmark's own o, moved into the zero's slot ----
# shoopi -> sho0pi. The resting glyph is literally the first o duplicated, so both
# states come from one drawing and there is nothing to register between sources.
base = traces["wordmark"]
glyphs = base.glyphs()
o_box, zero_box = base.bbox(glyphs[O]), base.bbox(glyphs[ZERO])
dx = (zero_box[0] + zero_box[1])/2 - (o_box[0] + o_box[1])/2   # same baseline, so no dy

smile, letters = base._split_ink()
zero_mask = glyphs[ZERO]
rest = letters & ~zero_mask

REST = "transition-all duration-300 ease-out motion-reduce:transition-none [transform-box:fill-box] origin-center"
layers = "".join(
    f'\n      <path fill="{c}" fillRule="evenodd" d="{d}" />'
    for c, d in (
        (PAPER, base.face()),
        (FILL[1], base.path(base.lab == 1, "blue", 1.0)),
        (FILL[2], base.path(base.lab == 2, "coral", 1.0)),
        (FILL[3], base.path(base.lab == 3, "violet", 0.6)),
        (FILL[INK], base.path(smile, "smile", 0.6)),
        (FILL[INK], base.path(rest, "rest", 0.6)),
    ))

tsx = f'''/* Generated by logo/build-wordmark.py - do not edit by hand.

   The sho0pi wordmark, with the o -> 0 morph the handle is named for. At rest the
   second glyph is the wordmark's own first o, copied across; hovering the hero
   crossfades it into the slashed zero. So the word reads shoopi until you touch it.
   Only that glyph swaps - every other letter is a single shared path, and both
   states come from the same drawing, so nothing can drift. Inline rather than an
   <img> because CSS has to reach the two groups. */
export function Wordmark({{ className }}: {{ className?: string }}) {{
  return (
    <svg
      viewBox="0 0 {base.w} {base.h}"
      className={{className}}
      role="img"
      aria-label="sho0pi"
    >{layers}
      <g className="{REST} group-hover:scale-75 group-hover:opacity-0 group-hover:blur-[4px] group-active:scale-75 group-active:opacity-0 group-active:blur-[4px]">
        <path
          fill="{FILL[INK]}"
          fillRule="evenodd"
          transform="translate({dx:.2f} 0)"
          d="{base.path(glyphs[O], "o-copy", 0.6)}"
        />
      </g>
      <g className="{REST} scale-125 opacity-0 blur-[4px] group-hover:scale-100 group-hover:opacity-100 group-hover:blur-none group-active:scale-100 group-active:opacity-100 group-active:blur-none">
        <path fill="{FILL[INK]}" fillRule="evenodd" d="{base.path(zero_mask, "zero", 0.6)}" />
      </g>
    </svg>
  );
}}
'''
open(os.path.join(ROOT, "components/wordmark.tsx"), "w").write(tsx)
print(f"morph: o copied into the zero slot, translate({dx:.2f} 0)")
